name: Workflow
on:
  push:
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install SonarCloud Scanner locally
      run: npm install sonar-scanner --save-dev
    

    - name: Run SonarCloud analysis
      run: |
        npx sonar-scanner \
        -Dsonar.projectKey=${{ github.event.repository.name }} \
        -Dsonar.organization=dusankm \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.branch.name=feat-devsecops